version: 2.17
jobs:
  build:
    branches:
      only:
        - development
    docker:
      - image: circleci/node:10.0.0
    working_directory: ~/project/
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - ./node_modules

workflows:
  version: 2
  build:
    jobs:
      - build